import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { QueryClientProvider } from "@tanstack/react-query";
import queryClient from "@/lib/reactQueryClient";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import "./globals.css";
import { getServerSession, Session } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/authOptions";
import Provider from "@/components/Provider";
import { Toaster } from "@/components/ui/toaster";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: Session | null = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${robotoSans.variable} ${robotoSans.variable} antialiased`}
      >
        <div className="flex h-screen w-screen overflow-auto">
          <main className="w-full h-full grow">
            <QueryClientProvider client={queryClient}>
              <Provider session={session}>
                {children}
                <ReactQueryDevtools initialIsOpen={false} />
              </Provider>
            </QueryClientProvider>
          </main>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
